disabled_rules:
  - trailing_whitespace
  - line_length
  - file_length
  - type_body_length
  - function_body_length
  - trailing_comma
  - opening_brace
  - multiple_closures_with_trailing_closure
  - large_tuple
  - todo

opt_in_rules:
  - force_unwrapping
  - empty_count

excluded:
  - DerivedData
  - Pods
  - .build

identifier_name:
  min_length: 2
  excluded:
    - id
    - db
    - i
    - j
    - k
    - x
    - y
    - z
    - t
    - v
    - f
    - p
    - c
    - s

type_name:
  min_length: 2