# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do

  lane :beta do
    api_key = app_store_connect_api_key(
      key_id: "8G5S826A9S",         # ton Key ID
      issuer_id: "8f04182c-ac4f-4df1-a0ef-d90da9863351",  # ton Issuer ID
      key_filepath: "./AuthKey_8G5S826A9S.p8"  # chemin vers ton .p8
    )

    increment_build_number(
      build_number: latest_testflight_build_number(api_key: api_key) + 1
    )

    build_app(
      scheme: "HolyDay",
      export_method: "app-store"
    )

    upload_to_testflight(
      api_key: api_key,
      skip_waiting_for_build_processing: true
    )
  end

end